### ISSUE TITLE
Can't read swagger JSON from http://localhost/connect/swagger/default/json

### ISSUE THREAD

**Issue by urfusion** [gbksoft/yii2-swagger#2]
> exception 'yii\web\NotFoundHttpException' in D:\xampp\htdocs\connect\vendor\gbksoft\yii2-swagger\controllers\DefaultController.php:154 Stack trace: #0 [internal function]: gbksoft\modules\swagger\controllers\DefaultController->actionJson() #1 D:\xampp\htdocs\connect\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #2 D:\xampp\htdocs\connect\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array) #3 D:\xampp\htdocs\connect\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('json', Array) #4 D:\xampp\htdocs\connect\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('swagger/default...', Array) #5 D:\xampp\htdocs\connect\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request)) #6 D:\xampp\htdocs\connect\index.php(12): yii\base\Application->run() #7 {main}

**Comment by azinkey** [comment]
i am also facing same issue

**Comment by littlefuntik** [comment]
You are must ckeck module configuration value `swaggerPath`, becouse module actionJson have logic for check this path readable. See action logic [controllers/DefaultController.php:L154](https://github.com/gbksoft/yii2-swagger/blob/master/controllers/DefaultController.php#L154)

**Comment by urfusion** [comment]
I didn't have `swagger.json` in my whole project

**Comment by littlefuntik** [comment]
The file `swagger.json` must be present.
I want to draw your attention to event `on beforeJson` in https://github.com/gbksoft/yii2-swagger/blob/master/README.md

**Comment by urfusion** [comment]
There is no file. I am using yii2 basic on win 7 with xampp. 

I also tried that on ubuntu 16.04, AWS EC2 with Php 7. but same result :(

**Comment by littlefuntik** [comment]
> There is no file.

This extension do not work without `swagger.json` file

**Comment by urfusion** [comment]
and swagger file is not present in extension.

**Comment by littlefuntik** [comment]
> and swagger file is not present in extension.

yes. See example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-simple.json
